version: "3.4"

x-common-variables: &common-variables
  REACT_APP_SERVER_PORT: 8000

services:
  server:
    build: ./server
    environment:
      <<: *common-variables
      NODE_ENV: development
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    command: npm run dev
    depends_on:
      - vectordb

  client:
    build: ./client
    environment:
      <<: *common-variables
      NODE_PATH: src
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: npm run start

  vectordb:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      QDRANT__STORAGE__DISK_CACHE: "1" # Enable disk cache for performance

volumes:
  qdrant_storage:
