version: "3.4"

x-common-variables: &common-variables
  REACT_APP_SERVER_PORT: 8000

services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/usr/src/app

    environment:
      - EXPRESS_PORT=8000
    command: go run cmd/main.go -b 0.0.0.0
    depends_on:
      - vectordb

  client:
    build: ./client
    environment:
      <<: *common-variables
      NODE_PATH: src
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: npm run start

  vectordb:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      QDRANT__STORAGE__DISK_CACHE: "1" # Enable disk cache for performance

  nitter:
    image: ghcr.io/sekai-soft/nitter-self-contained
    container_name: nitter
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - nitter-data:/nitter-data
      - ./twitter-credentials.json:/nitter-data/twitter-credentials.json
    # - ./nitter.conf:/src/nitter.conf
    depends_on:
      nitter-redis:
        condition: service_healthy
    environment:
      - NITTER_ACCOUNTS_FILE=/nitter-data/guest_accounts.json
      - DISABLE_REDIS=1
      - DISABLE_NGINX=1
      - DEBUG=1
      - REDIS_HOST=nitter-redis
      - TWITTER_CREDENTIALS_FILE=/nitter-data/twitter-credentials.json
    # - USE_CUSTOM_CONF=1
    #env_file:
    #  - .env
    restart: unless-stopped
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:8080 || exit 1
      interval: 5s
      timeout: 5s
      retries: 12
  nitter-redis:
    image: redis:6-alpine
    container_name: redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - nitter-redis:/data
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 5s
      retries: 12
  gmaps:
    build:
      context: ./gmaps  # or wherever your Dockerfile + gmaps_server.py is
    ports:
      - "8081:8081"
    env_file:
      - ./gmaps/.env

volumes:
  qdrant_storage:
  nitter-data:
  nitter-redis:
